import index from '@/data/pokemon-index.json';
import { EASY_POKEMON_IDS, MEDIUM_POKEMON_IDS } from '@/data/pokemon-difficulty';
import type { Difficulty, PokemonData } from './game-state';

export const GENERATIONS = [1, 2, 3, 4, 5, 6, 7, 8, 9] as const;
export const REGIONS: Record<number, string> = {
  1: 'Kanto', 2: 'Johto', 3: 'Hoenn', 4: 'Sinnoh', 5: 'Unova', 6: 'Kalos', 7: 'Alola', 8: 'Galar', 9: 'Paldea',
};
export const TYPES = [
  'normal', 'fire', 'water', 'grass', 'electric', 'ice', 'fighting', 'poison', 'ground',
  'flying', 'psychic', 'bug', 'rock', 'ghost', 'dragon', 'dark', 'steel', 'fairy',
] as const;
export type PokemonType = (typeof TYPES)[number];

export interface PoolFilters {
  /** Empty means every generation. */
  generations: readonly number[];
  /** Empty means every type; otherwise a Pokémon matches if it has any listed type. */
  types: readonly string[];
}

// Official artwork and sprites are served from the PokeAPI/sprites repo, so no API call is
// needed at runtime. The index is generated by scripts/generate-pokemon-data.mjs.
const SPRITES = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';

type SpeciesRow = [id: number, name: string, generation: number, types: string[]];
type FormRow = [id: number, name: string, speciesId: number, generation: number, types: string[]];

const species = index.species as SpeciesRow[];
const forms = index.forms as FormRow[];

const nameById = new Map<number, string>([...species, ...forms].map(([id, name]) => [id, name]));
const infoById = new Map<number, { generation: number; types: string[] }>([
  ...species.map(([id, , generation, types]) => [id, { generation, types }] as const),
  ...forms.map(([id, , , generation, types]) => [id, { generation, types }] as const),
]);

/** Generation and types, used by filters and hints. */
export function getPokemonInfo(id: number): { generation: number; types: string[] } | null {
  return infoById.get(id) ?? null;
}

export function artworkUrl(id: number): string {
  return `${SPRITES}/other/official-artwork/${id}.png`;
}

const CRIES = 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest';

export function cryUrl(id: number): string {
  return `${CRIES}/${id}.ogg`;
}

const speciesByForm = new Map<number, number>(forms.map(([id, , speciesId]) => [id, speciesId]));

/** The species a form belongs to (a species is its own). */
export function speciesOf(id: number): number {
  return speciesByForm.get(id) ?? id;
}

export function getPokemon(id: number): PokemonData | null {
  const name = nameById.get(id);
  if (!name) return null;
  return { id, name, artworkUrl: artworkUrl(id) };
}

const HARD_POOL: readonly number[] = [...species.map(([id]) => id), ...forms.map(([id]) => id)];

export const NO_FILTERS: PoolFilters = { generations: [], types: [] };

export function getPokemonPool(difficulty: Difficulty, filters: PoolFilters = NO_FILTERS): readonly number[] {
  const base = difficulty === 'easy' ? EASY_POKEMON_IDS : difficulty === 'medium' ? MEDIUM_POKEMON_IDS : HARD_POOL;
  if (filters.generations.length === 0 && filters.types.length === 0) return base;
  return base.filter((id) => {
    const info = infoById.get(id);
    if (!info) return false;
    if (filters.generations.length && !filters.generations.includes(info.generation)) return false;
    if (filters.types.length && !info.types.some((t) => filters.types.includes(t))) return false;
    return true;
  });
}

export function pickRandomPokemon(
  difficulty: Difficulty,
  excludeIds: readonly number[] = [],
  filters: PoolFilters = NO_FILTERS,
): PokemonData {
  const filtered = getPokemonPool(difficulty, filters);
  // A filter that matches nothing falls back to the whole difficulty rather than failing.
  const pool = filtered.length > 0 ? filtered : getPokemonPool(difficulty);
  const excluded = new Set(excludeIds);
  const available = pool.filter((id) => !excluded.has(id));
  const pickFrom = available.length > 0 ? available : pool;
  const id = pickFrom[Math.floor(Math.random() * pickFrom.length)];
  return getPokemon(id)!;
}

/**
 * Folds a name to a comparable key: case, accents, gender symbols and punctuation are ignored,
 * so "mr mime", "Mr. Mime" and "MR-MIME" all match, as do "flabebe" and "Flabébé".
 */
export function normalizeName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/♀/g, 'f')
    .replace(/♂/g, 'm')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function isCorrectGuess(guess: string, answer: string): boolean {
  const g = normalizeName(guess);
  return g.length > 0 && g === normalizeName(answer);
}

interface NameEntry {
  name: string;
  key: string;
  wordKeys: string[];
}

const ALL_NAMES: NameEntry[] = [...new Set([...species, ...forms].map(([, name]) => name))]
  .sort((a, b) => a.localeCompare(b))
  .map((name) => ({
    name,
    key: normalizeName(name),
    wordKeys: name.split(/[\s-]+/).map(normalizeName).filter(Boolean),
  }));

/**
 * Autocomplete for guesses. Names starting with the query come first, alphabetically; after
 * them come names with a later word starting with it, so "char" also offers "Mega Charizard X".
 */
export function searchPokemonNames(query: string, limit = 8): string[] {
  const q = normalizeName(query);
  if (!q) return [];
  const starts: string[] = [];
  const wordStarts: string[] = [];
  for (const entry of ALL_NAMES) {
    if (entry.key.startsWith(q)) starts.push(entry.name);
    else if (entry.wordKeys.some((w) => w.startsWith(q))) wordStarts.push(entry.name);
    if (starts.length >= limit) break;
  }
  return [...starts, ...wordStarts].slice(0, limit);
}

export interface DexEntryInfo {
  id: number;
  name: string;
  /** National Dex number; alternate forms share their species' number. */
  number: number;
  generation: number;
  types: string[];
}

/** Every Pokémon and form in National Dex order, each form right after its species. */
export const DEX_ORDER: readonly DexEntryInfo[] = (() => {
  const formsBySpecies = new Map<number, FormRow[]>();
  for (const f of forms) formsBySpecies.set(f[2], [...(formsBySpecies.get(f[2]) ?? []), f]);
  const out: DexEntryInfo[] = [];
  for (const [id, name, generation, types] of [...species].sort((a, b) => a[0] - b[0])) {
    out.push({ id, name, number: id, generation, types });
    for (const [fid, fname, , fgen, ftypes] of formsBySpecies.get(id) ?? []) {
      out.push({ id: fid, name: fname, number: id, generation: fgen, types: ftypes });
    }
  }
  return out;
})();
