import index from '@/data/pokemon-index.json';
import { EASY_POKEMON_IDS, MEDIUM_POKEMON_IDS } from '@/data/pokemon-difficulty';
import type { Difficulty, PokemonData } from './game-state';

// Official artwork and sprites are served from the PokeAPI/sprites repo, so no API call is
// needed at runtime. The index is generated by scripts/generate-pokemon-data.mjs.
const SPRITES = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon';

type SpeciesRow = [id: number, name: string];
type FormRow = [id: number, name: string, speciesId: number];

const species = index.species as SpeciesRow[];
const forms = index.forms as FormRow[];

const nameById = new Map<number, string>([...species, ...forms].map(([id, name]) => [id, name]));

export function artworkUrl(id: number): string {
  return `${SPRITES}/other/official-artwork/${id}.png`;
}

export function getPokemon(id: number): PokemonData | null {
  const name = nameById.get(id);
  if (!name) return null;
  return { id, name, artworkUrl: artworkUrl(id) };
}

const HARD_POOL: readonly number[] = [...species.map(([id]) => id), ...forms.map(([id]) => id)];

export function getPokemonPool(difficulty: Difficulty): readonly number[] {
  if (difficulty === 'easy') return EASY_POKEMON_IDS;
  if (difficulty === 'medium') return MEDIUM_POKEMON_IDS;
  return HARD_POOL;
}

export function pickRandomPokemon(difficulty: Difficulty, excludeIds: readonly number[] = []): PokemonData {
  const pool = getPokemonPool(difficulty);
  const excluded = new Set(excludeIds);
  const available = pool.filter((id) => !excluded.has(id));
  const pickFrom = available.length > 0 ? available : pool;
  const id = pickFrom[Math.floor(Math.random() * pickFrom.length)];
  return getPokemon(id)!;
}

/**
 * Folds a name to a comparable key: case, accents, gender symbols and punctuation are ignored,
 * so "mr mime", "Mr. Mime" and "MR-MIME" all match, as do "flabebe" and "Flabébé".
 */
export function normalizeName(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/♀/g, 'f')
    .replace(/♂/g, 'm')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function isCorrectGuess(guess: string, answer: string): boolean {
  const g = normalizeName(guess);
  return g.length > 0 && g === normalizeName(answer);
}

interface NameEntry {
  name: string;
  key: string;
  wordKeys: string[];
}

const ALL_NAMES: NameEntry[] = [...new Set([...species, ...forms].map(([, name]) => name))]
  .sort((a, b) => a.localeCompare(b))
  .map((name) => ({
    name,
    key: normalizeName(name),
    wordKeys: name.split(/[\s-]+/).map(normalizeName).filter(Boolean),
  }));

/**
 * Autocomplete for guesses. Names starting with the query come first, alphabetically; after
 * them come names with a later word starting with it, so "char" also offers "Mega Charizard X".
 */
export function searchPokemonNames(query: string, limit = 8): string[] {
  const q = normalizeName(query);
  if (!q) return [];
  const starts: string[] = [];
  const wordStarts: string[] = [];
  for (const entry of ALL_NAMES) {
    if (entry.key.startsWith(q)) starts.push(entry.name);
    else if (entry.wordKeys.some((w) => w.startsWith(q))) wordStarts.push(entry.name);
    if (starts.length >= limit) break;
  }
  return [...starts, ...wordStarts].slice(0, limit);
}
